name: stopwatch
version: 0.1
summary: stopwatch
description: stopwatch
type: app
confinement: devmode
icon: stopwatch.png
grade: devel
apps:
    stopwatch:
        command: stopwatch
        plugs: [opengl, x11]
parts:
    stopwatch:
        plugin: make
        source: .
        build-packages: [libglfw3-dev, libgles2-mesa-dev, xserver-xorg-video-all]
        stage-packages: [libglfw3, libgles2-mesa, xserver-xorg-video-all]
